from __future__ import annotations

from sqlalchemy import select

from app.db.init_db import init_db
from app.db.session import SessionLocal
from app.models import Product

PRODUCTS = [
    {
        "sku": "NB-PRO-14",
        "name": "NovaBook Pro 14",
        "brand": "Nova",
        "category": "Laptops",
        "short_description": "Compact performance laptop for work and creative workflows.",
        "description": "A lightweight professional laptop designed for productivity, development, media work, and everyday use.",
        "price": 1499.00,
        "original_price": 1599.00,
        "stock": 18,
        "image_url": "/products/laptop.svg",
        "rating": 4.7,
        "review_count": 184,
        "featured": True,
        "specifications": {
            "display": "14-inch 2560x1600",
            "processor": "8-core processor",
            "memory": "16GB",
            "storage": "512GB SSD",
            "battery": "Up to 15 hours",
        },
    },
    {
        "sku": "NB-AIR-13",
        "name": "NovaBook Air 13",
        "brand": "Nova",
        "category": "Laptops",
        "short_description": "Slim everyday laptop with a bright display and quiet cooling.",
        "description": "A thin and efficient laptop built for notes, browsing, content work, and travel-friendly productivity.",
        "price": 1199.00,
        "original_price": 1299.00,
        "stock": 22,
        "image_url": "/products/laptop.svg",
        "rating": 4.6,
        "review_count": 142,
        "featured": True,
        "specifications": {
            "display": "13.6-inch Retina-style display",
            "processor": "6-core processor",
            "memory": "16GB",
            "storage": "512GB SSD",
            "battery": "Up to 17 hours",
        },
    },
    {
        "sku": "VX-GAME-15",
        "name": "Vertex Gaming 15",
        "brand": "Vertex",
        "category": "Laptops",
        "short_description": "High-refresh gaming laptop with balanced thermals.",
        "description": "A performance-focused gaming laptop tuned for smooth frame rates, fast storage, and immersive play.",
        "price": 1699.00,
        "original_price": 1849.00,
        "stock": 9,
        "image_url": "/products/laptop.svg",
        "rating": 4.5,
        "review_count": 96,
        "featured": False,
        "specifications": {
            "display": "15.6-inch 165Hz display",
            "graphics": "Dedicated graphics",
            "memory": "16GB",
            "storage": "1TB SSD",
            "cooling": "Dual-fan thermal design",
        },
    },
    {
        "sku": "WM-PRO-16",
        "name": "WorkMate Pro 16",
        "brand": "WorkMate",
        "category": "Laptops",
        "short_description": "Large-screen laptop built for multitasking and spreadsheets.",
        "description": "A roomy 16-inch laptop that gives professionals more screen space for complex projects and extended sessions.",
        "price": 1599.00,
        "original_price": None,
        "stock": 14,
        "image_url": "/products/laptop.svg",
        "rating": 4.4,
        "review_count": 88,
        "featured": False,
        "specifications": {
            "display": "16-inch 2560x1600",
            "processor": "8-core processor",
            "memory": "32GB",
            "storage": "1TB SSD",
            "battery": "Up to 13 hours",
        },
    },
    {
        "sku": "VP-27-4K",
        "name": "VisionPro 27-inch 4K Monitor",
        "brand": "VisionPro",
        "category": "Monitors",
        "short_description": "Sharp 4K monitor for creative work and productivity.",
        "description": "A color-accurate 27-inch display with premium clarity, comfortable ergonomics, and clean desktop appeal.",
        "price": 499.00,
        "original_price": 549.00,
        "stock": 12,
        "image_url": "/products/monitor.svg",
        "rating": 4.8,
        "review_count": 203,
        "featured": True,
        "specifications": {
            "display": "27-inch 4K UHD",
            "panel": "IPS",
            "refresh_rate": "60Hz",
            "brightness": "350 nits",
            "ports": "HDMI, DisplayPort, USB-C",
        },
    },
    {
        "sku": "UW-34",
        "name": "UltraWide 34-inch Monitor",
        "brand": "Vista",
        "category": "Monitors",
        "short_description": "Wide curved monitor for timelines and split-screen workflows.",
        "description": "An ultrawide workspace display that makes multitasking and immersive viewing feel effortless.",
        "price": 699.00,
        "original_price": 749.00,
        "stock": 7,
        "image_url": "/products/monitor.svg",
        "rating": 4.7,
        "review_count": 121,
        "featured": False,
        "specifications": {
            "display": "34-inch ultrawide curved",
            "panel": "VA",
            "refresh_rate": "100Hz",
            "aspect_ratio": "21:9",
            "ports": "USB-C, HDMI, DisplayPort",
        },
    },
    {
        "sku": "SV-24-IPS",
        "name": "StudioView 24-inch IPS Monitor",
        "brand": "StudioView",
        "category": "Monitors",
        "short_description": "Affordable IPS monitor with a clean stand and vivid color.",
        "description": "A versatile 24-inch display for desks that need a reliable second screen or a compact primary monitor.",
        "price": 229.00,
        "original_price": None,
        "stock": 26,
        "image_url": "/products/monitor.svg",
        "rating": 4.5,
        "review_count": 67,
        "featured": False,
        "specifications": {
            "display": "24-inch Full HD",
            "panel": "IPS",
            "refresh_rate": "75Hz",
            "brightness": "300 nits",
            "ports": "HDMI, VGA",
        },
    },
    {
        "sku": "NK-MECH",
        "name": "NovaKeys Mechanical Keyboard",
        "brand": "NovaKeys",
        "category": "Keyboards",
        "short_description": "Tactile mechanical keyboard for typing and gaming.",
        "description": "A full-size mechanical keyboard with satisfying switches, durable keycaps, and understated styling.",
        "price": 149.00,
        "original_price": 169.00,
        "stock": 24,
        "image_url": "/products/keyboard.svg",
        "rating": 4.8,
        "review_count": 311,
        "featured": True,
        "specifications": {
            "layout": "Full-size 104-key",
            "switches": "Tactile mechanical switches",
            "lighting": "White backlight",
            "connectivity": "Wired USB-C",
        },
    },
    {
        "sku": "NK-MINI-WL",
        "name": "NovaKeys Mini Wireless Keyboard",
        "brand": "NovaKeys",
        "category": "Keyboards",
        "short_description": "Compact wireless keyboard for minimalist setups.",
        "description": "A space-saving keyboard that keeps desks tidy while still offering comfortable typing and mobile pairing.",
        "price": 99.00,
        "original_price": None,
        "stock": 17,
        "image_url": "/products/keyboard.svg",
        "rating": 4.4,
        "review_count": 103,
        "featured": False,
        "specifications": {
            "layout": "65%",
            "switches": "Low-profile quiet switches",
            "battery": "Rechargeable battery",
            "connectivity": "Bluetooth and 2.4GHz",
        },
    },
    {
        "sku": "PT-LP",
        "name": "ProType Low Profile Keyboard",
        "brand": "ProType",
        "category": "Keyboards",
        "short_description": "Slim keyboard with a laptop-like typing feel.",
        "description": "A low-profile keyboard that blends fast, quiet typing with a polished desktop footprint.",
        "price": 119.00,
        "original_price": 129.00,
        "stock": 11,
        "image_url": "/products/keyboard.svg",
        "rating": 4.6,
        "review_count": 86,
        "featured": False,
        "specifications": {
            "layout": "Full-size",
            "switches": "Low-profile membrane",
            "lighting": "Soft white backlight",
            "connectivity": "USB-C and Bluetooth",
        },
    },
    {
        "sku": "PW-MOUSE",
        "name": "Precision Wireless Mouse",
        "brand": "Precision",
        "category": "Mice",
        "short_description": "Compact mouse with quiet clicks and precise tracking.",
        "description": "An everyday wireless mouse tuned for smooth navigation, long battery life, and a comfortable hand feel.",
        "price": 79.00,
        "original_price": None,
        "stock": 31,
        "image_url": "/products/mouse.svg",
        "rating": 4.5,
        "review_count": 152,
        "featured": False,
        "specifications": {
            "sensor": "High-precision optical",
            "buttons": "6 programmable buttons",
            "battery": "AA battery",
            "connectivity": "2.4GHz wireless",
        },
    },
    {
        "sku": "PT-ERG",
        "name": "ProTrack Ergonomic Mouse",
        "brand": "ProTrack",
        "category": "Mice",
        "short_description": "Ergonomic mouse shaped for long editing sessions.",
        "description": "A sculpted vertical mouse that helps reduce wrist strain while staying responsive for daily work.",
        "price": 89.00,
        "original_price": 99.00,
        "stock": 13,
        "image_url": "/products/mouse.svg",
        "rating": 4.6,
        "review_count": 91,
        "featured": False,
        "specifications": {
            "sensor": "Precision optical",
            "buttons": "5 programmable buttons",
            "battery": "Rechargeable battery",
            "connectivity": "Bluetooth",
        },
    },
    {
        "sku": "GM-X8",
        "name": "Gaming Mouse X8",
        "brand": "GameForge",
        "category": "Mice",
        "short_description": "Fast gaming mouse with adjustable DPI and RGB accents.",
        "description": "A responsive gaming mouse built for flick shots, quick macros, and reliable everyday use.",
        "price": 109.00,
        "original_price": 129.00,
        "stock": 8,
        "image_url": "/products/mouse.svg",
        "rating": 4.7,
        "review_count": 175,
        "featured": True,
        "specifications": {
            "sensor": "Gaming-grade optical",
            "buttons": "8 programmable buttons",
            "dpi": "Up to 16,000 DPI",
            "connectivity": "Wired USB-C",
        },
    },
    {
        "sku": "NS-WIRELESS",
        "name": "NovaSound Wireless Headphones",
        "brand": "NovaSound",
        "category": "Headphones",
        "short_description": "Balanced wireless headphones for work and downtime.",
        "description": "A comfortable pair of over-ear headphones with clean tuning, strong battery life, and everyday portability.",
        "price": 199.00,
        "original_price": 229.00,
        "stock": 19,
        "image_url": "/products/headphones.svg",
        "rating": 4.6,
        "review_count": 208,
        "featured": True,
        "specifications": {
            "driver": "40mm drivers",
            "battery": "Up to 30 hours",
            "connectivity": "Bluetooth 5.3",
            "charging": "USB-C",
        },
    },
    {
        "sku": "S-ANC",
        "name": "Studio ANC Headphones",
        "brand": "Studio",
        "category": "Headphones",
        "short_description": "Noise-canceling headphones for focused listening.",
        "description": "A tuned over-ear headset with active noise cancellation and a plush fit for long sessions.",
        "price": 279.00,
        "original_price": 299.00,
        "stock": 10,
        "image_url": "/products/headphones.svg",
        "rating": 4.8,
        "review_count": 147,
        "featured": False,
        "specifications": {
            "driver": "40mm dynamic drivers",
            "battery": "Up to 35 hours",
            "connectivity": "Bluetooth 5.3",
            "anc": "Adaptive noise cancellation",
        },
    },
    {
        "sku": "AB-PRO",
        "name": "AeroBuds Pro",
        "brand": "Aero",
        "category": "Headphones",
        "short_description": "Pocketable earbuds with a compact charging case.",
        "description": "True wireless earbuds with crisp audio, lightweight comfort, and quick pairing for mobile life.",
        "price": 159.00,
        "original_price": None,
        "stock": 27,
        "image_url": "/products/headphones.svg",
        "rating": 4.5,
        "review_count": 133,
        "featured": False,
        "specifications": {
            "driver": "Custom tuned drivers",
            "battery": "Up to 24 hours with case",
            "connectivity": "Bluetooth 5.3",
            "charging": "USB-C",
        },
    },
    {
        "sku": "SC-4K",
        "name": "StreamCam 4K",
        "brand": "StreamCam",
        "category": "Webcams",
        "short_description": "Sharp 4K webcam for streaming and calls.",
        "description": "A premium webcam with reliable autofocus and clean image quality for presentations and content creation.",
        "price": 189.00,
        "original_price": 209.00,
        "stock": 15,
        "image_url": "/products/webcam.svg",
        "rating": 4.7,
        "review_count": 112,
        "featured": False,
        "specifications": {
            "video": "4K at 30fps",
            "focus": "Autofocus",
            "microphone": "Dual noise-reducing mics",
            "mount": "Universal monitor clip",
        },
    },
    {
        "sku": "WC-FHD",
        "name": "WorkCam Full HD",
        "brand": "WorkCam",
        "category": "Webcams",
        "short_description": "Reliable 1080p webcam for everyday meetings.",
        "description": "A simple plug-and-play webcam that delivers dependable framing and clear audio for remote work.",
        "price": 89.00,
        "original_price": None,
        "stock": 21,
        "image_url": "/products/webcam.svg",
        "rating": 4.3,
        "review_count": 74,
        "featured": False,
        "specifications": {
            "video": "1080p at 60fps",
            "focus": "Fixed focus",
            "microphone": "Built-in microphone",
            "mount": "Adjustable clip",
        },
    },
    {
        "sku": "SSD-1TB",
        "name": "Portable SSD 1TB",
        "brand": "Flux",
        "category": "Storage",
        "short_description": "Pocket SSD for quick transfers and backups.",
        "description": "A compact SSD that balances speed, reliability, and a durable enclosure for travel and daily backups.",
        "price": 129.00,
        "original_price": 149.00,
        "stock": 28,
        "image_url": "/products/storage.svg",
        "rating": 4.8,
        "review_count": 194,
        "featured": True,
        "specifications": {
            "capacity": "1TB",
            "interface": "USB-C",
            "speed": "Up to 1,050 MB/s",
            "enclosure": "Anodized aluminum",
        },
    },
    {
        "sku": "SSD-2TB",
        "name": "Portable SSD 2TB",
        "brand": "Flux",
        "category": "Storage",
        "short_description": "High-capacity SSD for media libraries and projects.",
        "description": "A larger portable drive for creators and professionals who keep big assets on hand.",
        "price": 219.00,
        "original_price": 249.00,
        "stock": 14,
        "image_url": "/products/storage.svg",
        "rating": 4.7,
        "review_count": 108,
        "featured": False,
        "specifications": {
            "capacity": "2TB",
            "interface": "USB-C",
            "speed": "Up to 1,050 MB/s",
            "enclosure": "Anodized aluminum",
        },
    },
    {
        "sku": "DOCK-USB-C",
        "name": "USB-C Pro Dock",
        "brand": "DockLine",
        "category": "USB-C / Docking",
        "short_description": "All-in-one dock for modern laptops and desks.",
        "description": "A versatile dock with display outputs, card readers, and charging support for streamlined workstations.",
        "price": 159.00,
        "original_price": 179.00,
        "stock": 16,
        "image_url": "/products/dock.svg",
        "rating": 4.6,
        "review_count": 140,
        "featured": True,
        "specifications": {
            "ports": "11-in-1 expansion",
            "display": "Dual display support",
            "power": "100W pass-through charging",
            "body": "Aluminum enclosure",
        },
    },
    {
        "sku": "DOCK-TB",
        "name": "Thunderbolt Dock",
        "brand": "DockLine",
        "category": "USB-C / Docking",
        "short_description": "Fast docking station for high-bandwidth workflows.",
        "description": "A premium dock for users who need multiple high-speed peripherals and a clean desk setup.",
        "price": 249.00,
        "original_price": 279.00,
        "stock": 11,
        "image_url": "/products/dock.svg",
        "rating": 4.7,
        "review_count": 87,
        "featured": False,
        "specifications": {
            "ports": "Thunderbolt 4 docking",
            "display": "Dual 4K support",
            "power": "Up to 96W charging",
            "body": "Metal enclosure",
        },
    },
    {
        "sku": "CHG-100W",
        "name": "100W USB-C Charger",
        "brand": "ChargeLab",
        "category": "Accessories",
        "short_description": "Compact charger for laptops, tablets, and phones.",
        "description": "A reliable compact charger that keeps modern USB-C devices powered at a desk or in a bag.",
        "price": 69.00,
        "original_price": None,
        "stock": 34,
        "image_url": "/products/accessory.svg",
        "rating": 4.6,
        "review_count": 156,
        "featured": False,
        "specifications": {
            "output": "100W USB-C",
            "ports": "Single port",
            "form_factor": "Compact wall adapter",
            "cable": "Included USB-C cable",
        },
    },
    {
        "sku": "STAND-LAP",
        "name": "Laptop Stand",
        "brand": "Lift",
        "category": "Accessories",
        "short_description": "Aluminum stand for better posture and airflow.",
        "description": "A simple desktop stand that raises laptops to a comfortable height and keeps surfaces organized.",
        "price": 49.00,
        "original_price": 59.00,
        "stock": 40,
        "image_url": "/products/accessory.svg",
        "rating": 4.5,
        "review_count": 122,
        "featured": False,
        "specifications": {
            "material": "Anodized aluminum",
            "adjustment": "Fixed elevation",
            "compatibility": "Most 13-16 inch laptops",
            "finish": "Matte silver",
        },
    },
]


def upsert_product(db, payload: dict) -> None:
    product = db.scalar(select(Product).where(Product.sku == payload["sku"]))
    if product is None:
        product = Product(**payload)
        db.add(product)
        return

    for key, value in payload.items():
        setattr(product, key, value)


def main() -> None:
    init_db()
    db = SessionLocal()
    try:
        for payload in PRODUCTS:
            upsert_product(db, payload)
        db.commit()
        print(f"Seeded {len(PRODUCTS)} products.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
